from imports import SinglyLinkedListWithoutTail, SinglyLinkedListWithTail

sllwot = SinglyLinkedListWithoutTail()
sllwot.append(1)
sllwot.append(2)
sllwot.append(3)
sllwot.append(4)
sllwot.prepend(0)
sllwot.prepend(-1)
sllwot.insert_after(2, 2.5)
sllwot.delete_by_key(2)
sllwot.delete_by_position(0)
print(sllwot)

sllwt = SinglyLinkedListWithTail()
sllwt.append(1)
sllwt.append(2)
sllwt.append(3)
sllwt.append(4)
sllwt.prepend(0)
sllwt.prepend(-1)
sllwt.insert_after(2, 2.5)
sllwt.delete_by_key(2)
sllwt.delete_by_position(0)
print(sllwt)