from imports import SinglyLinkedListWithoutTail, SinglyLinkedListWithTail, \
    DoublyLinkedListWithoutTail, DoublyLinkedListWithTail

sllwot = SinglyLinkedListWithoutTail()
sllwot.append(1)
sllwot.append(2)
sllwot.append(3)
sllwot.append(4)
sllwot.prepend(0)
sllwot.prepend(-1)
sllwot.insert_after(2, 2.5)
sllwot.delete_by_key(2)
sllwot.delete_by_position(0)
print(sllwot)

sllwt = SinglyLinkedListWithTail()
sllwt.append(1)
sllwt.append(2)
sllwt.append(3)
sllwt.append(4)
sllwt.prepend(0)
sllwt.prepend(-1)
sllwt.insert_after(2, 2.5)
sllwt.delete_by_key(2)
sllwt.delete_by_position(0)
print(sllwt)

dllwot = DoublyLinkedListWithoutTail()
dllwot.append(1)
print(dllwot)
dllwot.append(2)
print(dllwot)
dllwot.append(3)
dllwot.append(4)
print(dllwot)
dllwot.prepend(0)
dllwot.prepend(-1)
print(dllwot)
dllwot.insert_after(2, 2.5)
dllwot.insert_after(4, 4.5)
print(dllwot)
dllwot.delete_by_key(-1)
dllwot.delete_by_key(4.5)
dllwot.delete_by_key(2)
print(dllwot)
dllwot.delete_by_position(0)
dllwot.delete_by_position(2)
print(dllwot)

dllwt = DoublyLinkedListWithTail()
dllwt.append(1)
print(dllwt)
dllwt.append(2)
print(dllwt)
dllwt.append(3)
dllwt.append(4)
print(dllwt)
dllwt.prepend(0)
dllwt.prepend(-1)
print(dllwt)
dllwt.insert_after(2, 2.5)
dllwt.insert_after(4, 4.5)
print(dllwt)
dllwt.delete_by_key(-1)
dllwt.delete_by_key(4.5)
dllwt.delete_by_key(2)
print(dllwt)
dllwt.delete_by_position(0)
dllwt.delete_by_position(2)
print(dllwt)